# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deadline', models.DateTimeField()),
                ('load', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(0, 'test'), (1, 'homework')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='week_scheduler.Course')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField()),
                ('load', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'semana',
                'verbose_name_plural': 'semanas',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='week_scheduler.Week'),
        ),
    ]
