# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('num_weeks', models.IntegerField(max_length=55)),
            ],
        ),
    ]
