# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_scheduler', '0006_auto_20171123_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='first_week',
            field=models.DateTimeField(default=None),
        ),
    ]
